name: Build and Deploy to RepoB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019  # or windows-2019 if you want Visual Studio 2019
    steps:
      - name: Checkout repoA
      - uses: actions/checkout@v3
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '16.0'  # Use Visual Studio 2019 (version 16.0)

      - name: Restore NuGet Packages
        run: nuget restore CSharp-TuT.sln

      - name: Build with MSBuild
        run: |
          msbuild.exe CSharp-TuT.sln /p:platform="Any CPU" /p:configuration="Release"
      
      name: Find DLL
      id: find-dll
      run: |
        $dllPath = Get-ChildItem -Recurse -Path . -Filter *.dll | Where-Object { $_.FullName -like "*bin\Release\*" } | Select-Object -First 1 -ExpandProperty FullName
        echo "::set-output name=dllPath::$dllPath"

      - name: Checkout RepoB
        uses: actions/checkout@v3
        with:
          repository: Giacogiak/RepoB
          token: ${{ secrets.REPOB_PAT }}

       - name: Copy DLL to repoB/plugins
      run: |
        Copy-Item -Path "${{ steps.find-dll.outputs.dllPath }}" -Destination "repoB/plugins/"

      - name: Commit and Push to RepoB
        run: |
          cd RepoB
          git config --global user.email "forcina.giacomo@gmail.com"
          git config --global user.name "Giacogiak"
          git add .
          git commit -m "Auto-update DLLs from RepoA" || echo "No changes to commit"
          git push
        shell: pwsh
