name: Build and Deploy to RepoB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.5.0

      - name: Restore Dependencies
        run: dotnet restore CSharp-TuT.sln

      - name: Build Solution
        run: dotnet build CSharp-TuT.sln --configuration Release --no-restore

      - name: Copy Artifacts
        run: |
          mkdir -p artifacts
          find . -type f \( -name "*.dll" -o -name "*.lib" \) -exec cp {} artifacts/ \;

      - name: Checkout RepoB
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPOB_PAT }}

      - name: Move Artifacts to RepoB
        run: |
          mkdir -p RepoB/libs
          cp -r artifacts/* RepoB/plugins/

      - name: Commit and Push to RepoB
        run: |
          cd RepoB
          git config --global user.email "forcina.giacomo@gmail.com"
          git config --global user.name "github-actions"
          git add libs/
          git commit -m "Auto-update DLLs from RepoA"
          git push
