name: Build and Deploy to RepoB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework

    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore CSharp-TuT.sln

      - name: Build with MSBuild
        run: |
          msbuild.exe CSharp-TuT.sln /p:platform="Any CPU" /p:configuration="Release"
      
      - name: Find and Copy DLLs and LIBs
        run: |
          mkdir -p artifacts
          Get-ChildItem -Path . -Include *.dll, *.lib -Recurse | Copy-Item -Destination artifacts -Force
        shell: pwsh

      - name: Checkout RepoB
        uses: actions/checkout@v3
        with:
          repository: Giacogiak/RepoB
          token: ${{ secrets.REPOB_PAT }}

      - name: Move Artifacts to RepoB
        run: |
          Copy-Item -Path artifacts/* -Destination RepoB/plugins/ -Recurse -Force
        shell: pwsh

      - name: Commit and Push to RepoB
        run: |
          cd RepoB
          git config --global user.email "forcina.giacomo@gmail.com"
          git config --global user.name "Giacogiak"
          git add .
          git commit -m "Auto-update DLLs from RepoA" || echo "No changes to commit"
          git push
        shell: pwsh
