name: Build and Deploy to RepoB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework

    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v3

       - name: Install .NET Framework 4.5 Developer Pack
        run: |
          choco install netfx-4.5-devpack -y --force
        shell: pwsh

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore RepoA.sln

      - name: Build with MSBuild
        run: msbuild CSharp-TuT.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Find and Copy DLLs and LIBs
        run: |
          mkdir -p artifacts
          Get-ChildItem -Path . -Include *.dll, *.lib -Recurse | Copy-Item -Destination artifacts -Force
        shell: pwsh

      - name: Checkout RepoB
        uses: actions/checkout@v3
        with:
          repository: your-username/RepoB
          token: ${{ secrets.REPOB_PAT }}

      - name: Move Artifacts to RepoB
        run: |
          mkdir -p RepoB/plugins
          Copy-Item -Path artifacts/* -Destination RepoB/plugins/ -Recurse -Force
        shell: pwsh

      - name: Commit and Push to RepoB
        run: |
          cd RepoB
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Auto-update DLLs from RepoA" || echo "No changes to commit"
          git push
        shell: pwsh
