name: Build and Deploy to RepoB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages
        run: nuget restore CSharp-TuT.sln

      - name: Build Solution
        run: msbuild CSharp-TuT.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Find and Copy DLLs and LIBs
        run: |
          mkdir -p artifacts
          Get-ChildItem -Path . -Include *.dll, *.lib -Recurse | Copy-Item -Destination artifacts -Force
        shell: pwsh

      - name: Checkout RepoB
        uses: actions/checkout@v3
        with:
          repository: Giacogiak/RepoB
          token: ${{ secrets.REPOB_PAT }}

      - name: Move Artifacts to RepoB
        run: |
          cp -r artifacts/* RepoB/plugins/

      - name: Commit and Push to RepoB
        run: |
          cd RepoB
          git config --global user.email "forcina.giacomo@gmail.com"
          git config --global user.name "github-actions"
          git commit -m "Auto-update DLLs from RepoA"
          git push
